spring.application.name=backend

# ==========================
# MySQL Database
# ==========================
spring.datasource.url=mysql://avnadmin:AVNS_N9b2gAPGFS3C7CrhUsI@mysql-7b660f0-adityaakumar3004-fa04.k.aivencloud.com:13553/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_N9b2gAPGFS3C7CrhUsI
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================
# JPA / Hibernate
# ==========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================
# Server
# ==========================
server.port=${PORT:5000}

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ==========================
# Email / Gmail SMTP
# ==========================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true